<?php
use Lns\Sb\Lib\Lang\Lang;
$house = $this->getHouse();
$_lang = new Lang();
?>
<div class="row">
  <div class="col-md-12">
    <div class="clearfix mB-20">
			<h4 class="c-grey-900 mB-0 pull-left"><?= $house ? 'Update house/building' : 'Add new house/building'; ?></h4>	
			<a href="<?= $this->getAdminUrl('/house') ?>">
				<button type="button" class="btn cur-p btn-success pull-right">
					<?= $_lang->getLang('back'); ?>
				</button>
			</a>
		</div>
  </div>
	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="card bd bdrs-3 pX-30 pY-25 mB-20 mB-20">
			<h6 class="c-grey-900 mB-20">Basic Info.</h6>
			<form action="<?= $this->getAdminUrl('house/action/save') ?>" method="POST">
				<input type="hidden" name="id" value="<?= $house ? $house->getData('id') : '' ?>" />
				<div class="form-group row">
					<label class="col-sm-2 col-form-label" for="house-name">
                    House/Building no.
					</label>
					<div class="col-md-10">
						<input 
							type="text" 
							class="form-control" 
							id="house-name" 
							name="house_name" 
							value="<?= $house ? $house->getData('house_name') : '' ?>" 
							required="required"
						/>
					</div>
				</div>
                <div class="form-group row">
					<label class="col-sm-2 col-form-label" for="capacity">
                    Chicken Capacity
					</label>
					<div class="col-md-10">
						<input 
							type="number" 
							class="form-control" 
							id="capacity" 
							name="capacity" 
							value="<?= $house ? $house->getData('capacity') : '' ?>" 
							required="required" 
                            min="0"
                            step="1"
						/>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-10">
						<button type="submit" class="btn btn-primary" value="1" name="save">
							<?= $_lang->getLang('save'); ?>
						</button>
					</div>
				</div>
			</form>
    	</div>
	</div>
</div>
